# Generated by Django 2.0.2 on 2018-04-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('doj', models.IntegerField(default=0)),
                ('department', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobie', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.IntegerField(default=0)),
                ('sub_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
    ]
